### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by kbvstmd** [LongTailBio/pangea-client#22]
![未命名1590475287](https://user-images.githubusercontent.com/10649675/82868444-3ea60a80-9f5f-11ea-9e73-92de40e26c65.png)
can you help me ,thanks!

**Comment by kbvstmd** [comment]
Creating an optimized production build...
Failed to compile.

/usr/src/app/src/contrib/metasub/components/samplesunburst.tsx
TypeScript error in /usr/src/app/src/contrib/metasub/components/samplesunburst.tsx(65,26):
Property 'value' does not exist on type 'PlotDatum'.  TS2339

    63 |         onClick={e =>
    64 |           props.onClickAction(
  > 65 |             e.points[0]?.value
       |                          ^
    66 |               ? e.points[0]?.label
    67 |                 ? e.points[0]?.label
    68 |                 : ''

**Comment by dcdanko** [comment]
See https://github.com/LongTailBio/pangea-client/issues/21


Unfortunately though I can't support custom deploys
